### ISSUE TITLE
Parse flags problem

### ISSUE THREAD

**Issue by yonatan** [drd/gumbo-node#1]
Gumbo's parse flags are actually a bit vector (they get ORed together), so the switch statement in `get_parse_flags()` can fall apart with an unknown parse flag exception.

I don't have a patch atm, but I think the thing to do is just pass the flags as an integer to javascript and maybe provide a js version of the _GumboParseFlags enum for library users.

**Comment by drd** [comment]
Thanks for the heads up, @yonatan!
